# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-20 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='profilePic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
