# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-20 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RA', '0002_auto_20190820_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Rory', max_length=255),
            preserve_default=False,
        ),
    ]
