# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-21 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RA', '0004_auto_20190820_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('shortName', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
