# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-21 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RA', '0007_auto_20190821_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='admins',
            field=models.ManyToManyField(related_name='Admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='club',
            field=models.ManyToManyField(related_name='ApprovedClub', to='RA.Club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='requestedClub',
            field=models.ManyToManyField(related_name='RequestedClub', to='RA.Club'),
        ),
    ]
