# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RA', '0010_auto_20190821_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='club',
            field=models.ManyToManyField(related_name='ApprovedClub', to='RA.Club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='requestedClub',
            field=models.ManyToManyField(related_name='RequestedClub', to='RA.Club'),
        ),
    ]
